DROP DATABASE IF EXISTS userdb;
CREATE DATABASE userdb;
USE userdb;

CREATE TABLE user(
    user_id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(60) NOT NULL,
    password VARCHAR(20) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

ALTER TABLE user 
    ADD COLUMN imgUrl MEDIUMTEXT 
;